Feature/community posts
aakb/itchefer pull request #185
Opened 2022-07-14 09:49 UTC by martinyde

Most relevant is the itchefer_stream module files

2022-07-14 14:07 UTC, rimi-itk requested changes
Looks good. Some minor issues should be fixed.

Is the change from `langcode: en` to `langcode: da` in config files something that we should worry about?

2022-07-14 14:07 UTC, rimi-itk commented on html/modules/custom/itchefer_stream/itchefer_stream.module
> +        $replacements[$token] = substr($currentValueStripped, 0, 150) . '...';
It seems odds to check if the length is more that 20 characters and then stripping to (at most) 150 characters? Shouldn't it be 150 (or 20) in both places?

2022-07-14 14:07 UTC, rimi-itk commented on html/modules/custom/itchefer_stream/src/Plugin/ActivityContext/CommunityActivityWithRecipientsContext.php
> +      }
For performance reasons the check for a deleted entity should be performed before getting all users (to get rid of an unnecessary database query for all user).

2022-07-14 14:07 UTC, rimi-itk commented on html/modules/custom/itchefer_stream/src/Plugin/ActivityContext/CommunityActivityWithRecipientsContext.php
> +    if (!isset($entity)) {
This check is inconsistent with the check in line 88. Use `!isset(…)` or `!…` (or `empty(…)` or `NULL === …`) consistently to check to a missing entity.

2022-07-14 14:07 UTC, rimi-itk commented on html/modules/custom/itchefer_stream/src/Plugin/ActivityContext/CommunityActivityWithRecipientsContext.php
> +      }
Writing this as 

```php
      if (!$entity->field_recipient_group->isEmpty()
        || !$entity->field_recipient_user->isEmpty()) {
        return FALSE;
      }
```

may make it a little easier to read.

2022-07-15 07:01 UTC, martinyde commented on html/modules/custom/itchefer_stream/itchefer_stream.module
> +        $replacements[$token] = substr($currentValueStripped, 0, 150) . '...';
Fixed

2022-07-15 07:02 UTC, martinyde commented on html/modules/custom/itchefer_stream/src/Plugin/ActivityContext/CommunityActivityWithRecipientsContext.php
> +      }
Fixed

2022-07-15 07:05 UTC, martinyde commented on html/modules/custom/itchefer_stream/src/Plugin/ActivityContext/CommunityActivityWithRecipientsContext.php
> +    if (!isset($entity)) {
Fixed

2022-07-15 07:05 UTC, martinyde commented on html/modules/custom/itchefer_stream/src/Plugin/ActivityContext/CommunityActivityWithRecipientsContext.php
> +      }
Fixed

2022-07-15 07:05 UTC, martinyde commented
No worries

2022-07-15 07:07 UTC, merged