Feature/itc 104 add link to create header 11 2020
aakb/itchefer pull request #32
Opened 2020-12-09 10:13 UTC by sinejespersen

https://jira.itkdev.dk/browse/ITC-104

2020-12-10 09:24 UTC, rimi-itk requested changes
Some comments should be fixed.

2020-12-10 09:24 UTC, rimi-itk commented on html/modules/custom/itchefer_link_in_create_header/itchefer_link_in_create_header.module
> + * The module for itchefer_event_enrollment.
Hide your tracks when you steal code.

2020-12-10 09:24 UTC, rimi-itk commented on html/modules/custom/itchefer_link_in_create_header/itchefer_link_in_create_header.module
> + * The Social event module.
Well, I'm not sure this description is accurate …

2020-12-10 11:17 UTC, sinejespersen commented on html/modules/custom/itchefer_link_in_create_header/itchefer_link_in_create_header.module
> + * The module for itchefer_event_enrollment.
haha hvor pinligt

2020-12-11 07:28 UTC, rimi-itk approved these changes

2020-12-11 07:36 UTC, merged